### ISSUE TITLE
[Chore] 세팅 관련 경고 문구 정리

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MacC-Team10-OFO#13]
## 💡 Issue
- 세팅관련 경고 문구를 해결하는 법을 정리합니다.

- 화면 잘림 문제: 
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-OFO/assets/36729917/fa3a91bd-547f-42de-b8cb-7248eff281bc)
사진처럼 타겟에서 launchscreenfile - LaunchScreen 텍스트 입력 후 저장
참조: https://stackoverflow.com/questions/65653708/why-doesnt-the-xcode-simulator-show-full-screen
- run script build phase 'run script' will be run during every build
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-OFO/assets/36729917/49b5f4fd-ca1c-427a-818e-f946bcc0876a)
사진처럼 프로젝트 각 모듈별 타겟 - Build Phases - SwiftLintString - based on dependency analyis 체크 해제 하시면 됩니다.

- The Swift file "/Users/hajongmyeong/Desktop/Project/MacC-Team10-OFO/Projects/Common/Resources/Dummy.swift" cannot be processed by a Copy Bundle Resources build phase
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team10-OFO/assets/36729917/a005d6a0-02df-449a-bb38-2761c0e5ca68)
- 사진처럼 Common_Common 타겟 - Copy Bundle Resources - Dummy.swift 파일 제외시키면 됩니다.

**Comment by hhajime** [comment]
궁금한것이 이런 과정을 거친 이후에,
프로젝트 새로 tuist fetch, generate 해오면 초기화가 되나요?

 git에서 세팅관련은 Tuist 특성상 추적이 되지 않아, 저장이 안될 경우가 걱정이에요.
초기화가 안되려면 새로 fetch해오는 과정은 지양해야 할 것 같네요.

**Comment by eemdeeks** [comment]
오 대박!
잘 찾아주셨네요 :]

초기화가 되는지는 아마 확인 해봐야할 거 같습니다ㅜㅜ 
tuist를 처음 써봐서 그런지 생각보다 불편한 점이 많네요.. 아직 익숙하지 않아서 그런가..

**Comment by hhajime** [comment]
어떤 문제 생기면 꼭 tuist 문제같아요 ..
이러다 신경쇠약 오겠어요

**Comment by eemdeeks** [comment]
ㅋㅋㅋ 처음 써봐서 tuist한테 피해의식 생길듯... 인정입니다

맥북을 껐다가 tuist generate 다시 실행 하니까 수동으로 해 놓은 설정들 다 리셋 되네요ㅜㅜ
